# Check that the executable can be built
name: Check build

on:
  push:
    paths:
      - .github/workflows/check_build.yaml
      - '**.pro'
      - '**.pri'
      - '**.cpp'
      - '**.h'
  pull_request:
  schedule:
  - cron: "0 0 21 * *"

jobs:
  check-build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      - name: Build
        run: qmake StaircaseCardCreatorConsole.pro

      - name: Check if file was created
        run: |
          if [ -f staircase_card_creator_console ]; then
            echo "File exists. Yay!"
          else
            echo "File does not exist"
            exit 1
          fi

      - name: Did the last step fail?
        if: ${{ failure() }}
        run: echo "Last step failed, so file must have maybe been created"
