# Check that the executable can be built
name: Check build

on:
  push:
    paths:
      - .github/workflows/check_build.yaml
      - '**.pro'
      - '**.pri'
      - '**.cpp'
      - '**.h'
  pull_request:
  schedule:
  - cron: "0 0 21 * *"

jobs:
  check-build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      - name: Download dependencies
        run: ./download_other_githubs.sh

      - name: qmake
        run: qmake StaircaseCardCreatorConsole.pro

      - name: Install boost
        run: sudo apt install libboost-all-dev
      #  uses: MarkusJx/install-boost@v2
      #  with:
      #    # A list of supported versions can be found here:
      #    # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
      #    boost_version: 1.87.0

      - name: make
        run: make

      - name: See results
        run: find .

      - name: Check if file was created
        run: |
          if [ -f StaircaseCardCreatorConsole ]; then
            echo "File exists. Yay!"
          else
            echo "File does not exist"
            exit 1
          fi

      - name: qmake
        run: qmake StaircaseCardCreatorDesktop.pro

      - name: make
        run: make

      - name: See results
        run: find .

      - name: Check if file was created
        run: |
          if [ -f StaircaseCardCreatorDesktop ]; then
            echo "File exists. Yay!"
          else
            echo "File does not exist"
            exit 1
          fi
