# Check that the executable can be built
name: Check build

on:
  push:
    paths:
      - .github/workflows/check_build.yaml
      - '**.pro'
      - '**.pri'
      - '**.cpp'
      - '**.h'
  pull_request:
  schedule:
  - cron: "0 0 21 * *"

jobs:
  check-build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      - name: Download dependencies
        run: ./download_other_githubs.sh

      - name: qmake
        run: qmake StaircaseCardCreatorConsole.pro

      - name: Install boost
        uses: MarkusJx/install-boost@v2
        with:
          # A list of supported versions can be found here:
          # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
          boost_version: 1.73.0
          boost_install_dir: /home/runner

      - name: scout
        run: cd ~; ls; cd -

      #- name: scout
      #  run: cd ~/runner; ls; cd -

      #- name: scout
      #  run: cd ~/runner/boost; ls; cd -

      - name: make
        run: make

      - name: See results
        run: find .

      - name: Check if file was created
        run: |
          if [ -f staircase_card_creator_console ]; then
            echo "File exists. Yay!"
          else
            echo "File does not exist"
            exit 1
          fi
